#!/bin/bash

apt-get install libxml2-dev python-dev

su - ubuntu <<UBUNTU
mkdir /home/ubuntu/Downloads
cd /home/ubuntu/Downloads
wget -O uwsgi-0.9.8.1.tar.gz http://projects.unbit.it/downloads/uwsgi-0.9.8.1.tar.gz
make
UBUNTU

cp uwsgi /usr/sbin/uwsgi

$SERVER_CONFIG=/home/ubuntu/server-config

link_files=(
    "/etc/init.d/uwsgi"
)

for file in "${link_files[@]}"
do
  ln -sf $SERVER_CONFIG$file $file
done

/etc/init.d/uwsgi restart
